services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grader
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+aiomysql://root:R14751485r@db:3306/mydb
      - SYNC_ENGINE=mysql+pymysql://root:R14751485r@db:3306/mydb
      - JWT_SECRET_KEY=n5n7k2V3w8QzJ1uX9pA4sT7eL0rB6yC5dF2hG8jK3mP0sW4vX
      - MEDIA_DIR=/app/media

    volumes:
      - media_volume:/app/media
    networks:
      - backend_net

volumes:
  media_volume:
    external: true

networks:
  backend_net:
    driver: bridge